-- MySQL Script generated by MySQL Workbench
-- 04/27/15 17:45:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Practica4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Practica4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Practica4` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Practica4` ;

-- -----------------------------------------------------
-- Table `Practica4`.`TIPO_BUS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Practica4`.`TIPO_BUS` (
  `TIPO_BUS` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_TIPO` VARCHAR(45) NOT NULL,
  `CAPACIDAD_TIPO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TIPO_BUS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Practica4`.`PUNTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Practica4`.`PUNTO` (
  `PUNTO` INT NOT NULL AUTO_INCREMENT,
  `UBICACION` INT NULL,
  PRIMARY KEY (`PUNTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Practica4`.`RUTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Practica4`.`RUTA` (
  `ORIGEN_RUTA` INT NOT NULL,
  `DESTINO_RUTA` INT NOT NULL,
  INDEX `FK_ORIGEN_RUTA_idx` (`ORIGEN_RUTA` ASC),
  INDEX `FK_DESTINO_RUTA_idx` (`DESTINO_RUTA` ASC),
  PRIMARY KEY (`ORIGEN_RUTA`, `DESTINO_RUTA`),
  CONSTRAINT `FK_ORIGEN_RUTA`
    FOREIGN KEY (`ORIGEN_RUTA`)
    REFERENCES `Practica4`.`PUNTO` (`PUNTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DESTINO_RUTA`
    FOREIGN KEY (`DESTINO_RUTA`)
    REFERENCES `Practica4`.`PUNTO` (`PUNTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Practica4`.`BUS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Practica4`.`BUS` (
  `BUS` INT NOT NULL AUTO_INCREMENT,
  `MODELO` VARCHAR(45) NULL,
  `TIPO` INT NOT NULL,
  `RUTA_ORIGEN` INT NULL,
  `RUTA_DESTINO` INT NULL,
  PRIMARY KEY (`BUS`),
  INDEX `FK_TIPO_BUS_idx` (`TIPO` ASC),
  INDEX `FK_RUTA_BUS_idx` (`RUTA_ORIGEN` ASC, `RUTA_DESTINO` ASC),
  CONSTRAINT `FK_TIPO_BUS`
    FOREIGN KEY (`TIPO`)
    REFERENCES `Practica4`.`TIPO_BUS` (`TIPO_BUS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RUTA_BUS`
    FOREIGN KEY (`RUTA_ORIGEN` , `RUTA_DESTINO`)
    REFERENCES `Practica4`.`RUTA` (`ORIGEN_RUTA` , `DESTINO_RUTA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Practica4`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Practica4`.`CLIENTE` (
  `CLIENTE` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `APELLIDO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Practica4`.`PUNTO_RUTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Practica4`.`PUNTO_RUTA` (
  `RUTA_INICIO` INT NOT NULL,
  `RUTA_FIN` INT NOT NULL,
  `PUNTO` INT NOT NULL,
  `TIEMPO` TIME NOT NULL,
  PRIMARY KEY (`RUTA_INICIO`, `PUNTO`, `RUTA_FIN`),
  INDEX `FK_PUNTO_PUNTO_idx` (`PUNTO` ASC),
  INDEX `FK_RUTA_idx` (`RUTA_INICIO` ASC, `RUTA_FIN` ASC),
  CONSTRAINT `FK_PUNTO_PUNTO`
    FOREIGN KEY (`PUNTO`)
    REFERENCES `Practica4`.`PUNTO` (`PUNTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RUTA`
    FOREIGN KEY (`RUTA_INICIO` , `RUTA_FIN`)
    REFERENCES `Practica4`.`RUTA` (`ORIGEN_RUTA` , `DESTINO_RUTA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Practica4`.`VIAJE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Practica4`.`VIAJE` (
  `VIAJE` INT NOT NULL AUTO_INCREMENT,
  `ORIGEN_VIAJE_ORIGEN` INT NOT NULL,
  `ORIGEN_VIAJE_DESTINO` INT NOT NULL,
  `RUTA_ORIGEN` INT NOT NULL,
  `DESTINO_VIAJE_ORIGEN` INT NOT NULL,
  `DESTINO_VIAJE_DESTINO` INT NOT NULL,
  `RUTA_DESTINO` INT NOT NULL,
  `SALIDA` DATETIME NULL,
  `LLEGADA` DATETIME NULL,
  `CLIENTE` INT NULL,
  PRIMARY KEY (`VIAJE`),
  INDEX `FK_ORIGEN_VIAJE_idx` (`ORIGEN_VIAJE_ORIGEN` ASC, `RUTA_ORIGEN` ASC, `ORIGEN_VIAJE_DESTINO` ASC),
  INDEX `FK_DESTINO_VIAJE_idx` (`DESTINO_VIAJE_ORIGEN` ASC, `RUTA_DESTINO` ASC, `DESTINO_VIAJE_DESTINO` ASC),
  INDEX `FK_CLIENTE_VIAJE_idx` (`CLIENTE` ASC),
  CONSTRAINT `FK_ORIGEN_VIAJE`
    FOREIGN KEY (`ORIGEN_VIAJE_ORIGEN` , `RUTA_ORIGEN` , `ORIGEN_VIAJE_DESTINO`)
    REFERENCES `Practica4`.`PUNTO_RUTA` (`RUTA_INICIO` , `PUNTO` , `RUTA_FIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DESTINO_VIAJE`
    FOREIGN KEY (`DESTINO_VIAJE_ORIGEN` , `RUTA_DESTINO` , `DESTINO_VIAJE_DESTINO`)
    REFERENCES `Practica4`.`PUNTO_RUTA` (`RUTA_INICIO` , `PUNTO` , `RUTA_FIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CLIENTE_VIAJE`
    FOREIGN KEY (`CLIENTE`)
    REFERENCES `Practica4`.`CLIENTE` (`CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Practica4`.`FACTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Practica4`.`FACTURA` (
  `FACTURA` INT NOT NULL AUTO_INCREMENT,
  `FECHA` DATE NOT NULL,
  `CLIENTE` INT NOT NULL,
  `CANCELADA` TINYINT(1) NULL,
  PRIMARY KEY (`FACTURA`),
  INDEX `FK_CLIENTE_idx` (`CLIENTE` ASC),
  CONSTRAINT `FK_CLIENTE`
    FOREIGN KEY (`CLIENTE`)
    REFERENCES `Practica4`.`CLIENTE` (`CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Practica4`.`TICKET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Practica4`.`TICKET` (
  `TICKET` INT NOT NULL AUTO_INCREMENT,
  `FACTURA` INT NULL,
  `VIAJE` INT NOT NULL,
  `KILOMETRAJE` INT NULL,
  `PRECIO` INT NULL,
  PRIMARY KEY (`TICKET`),
  INDEX `FK_FACTURA_TICKET_idx` (`FACTURA` ASC),
  INDEX `FK_VIAJE_TICKET_idx` (`VIAJE` ASC),
  CONSTRAINT `FK_FACTURA_TICKET`
    FOREIGN KEY (`FACTURA`)
    REFERENCES `Practica4`.`FACTURA` (`FACTURA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_VIAJE_TICKET`
    FOREIGN KEY (`VIAJE`)
    REFERENCES `Practica4`.`VIAJE` (`VIAJE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Practica4`.`LOG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Practica4`.`LOG` (
  `LOG` INT NOT NULL AUTO_INCREMENT,
  `FECHA` DATE NOT NULL,
  `BUS` INT NOT NULL,
  `R_ORIGEN` INT NOT NULL,
  `R_DESTINO` INT NOT NULL,
  PRIMARY KEY (`LOG`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
